<?php
/**
 * AgriSense - Device management (requirement 16). Administrators only.
 */

class DeviceController extends Controller
{
    public function index(): void
    {
        Auth::requireLogin();

        Device::flagOfflineDevices();

        $devices = Device::all();

        // Per-device counters for the table.
        $summary = [];
        foreach ($devices as $d) {
            $id = (int) $d['id'];
            $summary[$id] = [
                'readings' => (int) Database::scalar(
                    'SELECT COUNT(*) FROM sensor_readings WHERE device_id = ?', [$id]
                ),
                'cycles' => (int) Database::scalar(
                    'SELECT COUNT(*) FROM irrigation_logs WHERE device_id = ?', [$id]
                ),
                'alerts' => (int) Database::scalar(
                    'SELECT COUNT(*) FROM alerts WHERE device_id = ? AND is_read = 0', [$id]
                ),
            ];
        }

        render('devices/index', [
            'devices' => $devices,
            'summary' => $summary,
            'isAdmin' => Auth::isAdmin(),
        ], ['title' => 'Devices', 'active' => 'devices']);
    }

    public function create(): void
    {
        Auth::requireAdmin();

        render('devices/form', [
            // A newly registered board is assumed to be running the current
            // firmware, which carries two probes and an MLX90614 rather than
            // a DHT22. Both switches are on the form for the older builds.
            'device' => ['device_name' => '', 'device_code' => '', 'mac_address' => '',
                         'location' => '', 'probe_count' => 2, 'has_dht22' => 0,
                         'has_mlx90614' => 1, 'status' => 'active'],
            'errors' => [],
            'isNew'  => true,
        ], ['title' => 'Register device', 'active' => 'devices']);
    }

    public function store(): void
    {
        Auth::requireAdmin();
        csrf_guard();

        $data = [
            'device_name' => input('device_name'),
            'device_code' => input('device_code'),
            'mac_address' => input('mac_address'),
            'location'    => input('location'),
            'probe_count' => input_int('probe_count', 1, 1, 2),
            'has_dht22'    => input('has_dht22') === '1' ? 1 : 0,
            'has_mlx90614' => input('has_mlx90614') === '1' ? 1 : 0,
            'status'       => one_of(input('status'), Device::STATUSES, 'active'),
        ];

        $errors = Device::validate($data);
        if ($errors) {
            render('devices/form', ['device' => $data, 'errors' => $errors, 'isNew' => true],
                ['title' => 'Register device', 'active' => 'devices']);

            return;
        }

        $plainKey = null;
        $id = Device::create($data, Auth::id(), $plainKey);

        SystemLog::record(Auth::id(), 'device_create',
            sprintf('Registered device %s (%s).', $data['device_code'], $data['device_name']));

        // Hand the key to the next request only. It is not recoverable
        // afterwards, so the edit page has to show it now or never.
        $_SESSION['_new_api_key'] = ['device_id' => $id, 'key' => $plainKey];

        flash('success', 'Device registered. Copy the API key below into the ESP32 firmware '
            . '- this is the only time it will be shown.');
        redirect('devices/edit', ['id' => $id]);
    }

    public function edit(): void
    {
        Auth::requireAdmin();

        $device = Device::find(input_int('id', 0, 1));
        if (!$device) {
            flash('danger', 'That device could not be found.');
            redirect('devices');
        }

        // A key generated by the previous request, shown once and then
        // discarded. Nothing can recover it after this render.
        $newKey = null;
        if (isset($_SESSION['_new_api_key'])
            && (int) $_SESSION['_new_api_key']['device_id'] === (int) $device['id']) {
            $newKey = $_SESSION['_new_api_key']['key'];
        }
        unset($_SESSION['_new_api_key']);

        render('devices/form', [
            'device'   => $device,
            'errors'   => [],
            'isNew'    => false,
            'newKey'   => $newKey,
            'settings' => IrrigationSetting::ensureFor((int) $device['id'], Auth::id()),
        ], ['title' => 'Edit device', 'active' => 'devices']);
    }

    public function update(): void
    {
        Auth::requireAdmin();
        csrf_guard();

        $id     = input_int('id', 0, 1);
        $device = Device::find($id);
        if (!$device) {
            flash('danger', 'That device could not be found.');
            redirect('devices');
        }

        $data = [
            'device_name' => input('device_name'),
            'device_code' => input('device_code'),
            'mac_address' => input('mac_address'),
            'location'    => input('location'),
            'probe_count' => input_int('probe_count', 1, 1, 2),
            'has_dht22'    => input('has_dht22') === '1' ? 1 : 0,
            'has_mlx90614' => input('has_mlx90614') === '1' ? 1 : 0,
            'status'       => one_of(input('status'), Device::STATUSES, 'active'),
        ];

        $errors = Device::validate($data, $id);
        if ($errors) {
            render('devices/form', [
                'device'   => array_merge($device, $data),
                'errors'   => $errors,
                'isNew'    => false,
                'settings' => IrrigationSetting::ensureFor($id),
            ], ['title' => 'Edit device', 'active' => 'devices']);

            return;
        }

        Device::update($id, $data);
        SystemLog::record(Auth::id(), 'device_update',
            sprintf('Updated device %s (status %s).', $data['device_code'], $data['status']));

        flash('success', 'Device updated.');
        redirect('devices/edit', ['id' => $id]);
    }

    /** Issue a fresh API key; the old one stops working immediately. */
    public function rotateKey(): void
    {
        Auth::requireAdmin();
        csrf_guard();

        $id     = input_int('id', 0, 1);
        $device = Device::find($id);
        if (!$device) {
            flash('danger', 'That device could not be found.');
            redirect('devices');
        }

        $plainKey = Device::rotateApiKey($id);
        SystemLog::record(Auth::id(), 'device_key_rotate',
            'Generated a new API key for ' . $device['device_code'] . '.');

        $_SESSION['_new_api_key'] = ['device_id' => $id, 'key' => $plainKey];

        flash('warning', 'A new API key was generated and is shown below - copy it now, '
            . 'it cannot be displayed again. Update the firmware on '
            . $device['device_code'] . '; the old key no longer works.');
        redirect('devices/edit', ['id' => $id]);
    }

    /**
     * Delete a device and everything recorded for it. Deactivating is
     * offered as the safer alternative in the UI.
     */
    public function delete(): void
    {
        Auth::requireAdmin();
        csrf_guard();

        $id     = input_int('id', 0, 1);
        $device = Device::find($id);
        if (!$device) {
            flash('danger', 'That device could not be found.');
            redirect('devices');
        }

        if (input('confirm_code') !== $device['device_code']) {
            flash('danger', 'Deletion cancelled - the device code you typed did not match.');
            redirect('devices/edit', ['id' => $id]);
        }

        $readings = (int) Database::scalar(
            'SELECT COUNT(*) FROM sensor_readings WHERE device_id = ?', [$id]
        );

        Device::delete($id);
        if ((int) ($_SESSION['device_id'] ?? 0) === $id) {
            unset($_SESSION['device_id']);
        }

        SystemLog::record(Auth::id(), 'device_delete', sprintf(
            'Deleted device %s along with %d sensor readings.', $device['device_code'], $readings
        ));

        flash('success', 'Device ' . $device['device_code'] . ' and its history were deleted.');
        redirect('devices');
    }
}
